version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./code:/code
      - ./code/instance/:/code/instance/
    command: python run.py
  sqlite3:
    image: nouchka/sqlite3
    stdin_open: true
    tty: true
    volumes:
      - ./code/instance/:/root/db/
